---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      env: development # adds this label
    includeSelectors: true # also add in selector matchLabels
    includeTemplates: true # also add in selector matchLabels

namePrefix: dev-
namespace: dev-myns

replicas:
  - name: dov-deploy
    count: 1

images:
  - name: chukmunnlee/cfdsa-dov-bear
    newName: chukmunnlee/dov-bear
    newTag: v5

patches:
  - target:
      version: apps/v1
      kind: Deployment
      name: dov-deploy
    path: patches.yaml
  - path: delete-ingress.yaml

replacements:
  - source:
      kind: Service
      name: dov-svc
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: dov-deploy
        fieldPaths:
          - spec.template.spec.containers.[name=dov-container].env.[name=SERVICE_NAME].value