---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      env: development # adds this label
    includeSelectors: true # also add in selector matchLabels
    includeTemplates: true # also add in selector matchLabels

namePrefix: dev-
namespace: dev-myns