---
# deployment for app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
    metadata:
      name: bggapp-po
      namespace: bggns # implied if unset here
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: bggapp-port
              containerPort: 3000
          # env:
          #   - name: BGG_DB_USER
          #     value: root
          #   - name: BGG_DB_HOST
          #     value: bggdb-svc.bggns.svc.cluster.local
          #   - name: BGG_DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: bggapp-secret
          #         key: BGG_DB_PASSWORD
          envFrom:
            - configMapRef:
                name: bggapp-cm
            - secretRef:
                name: bggapp-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: bggapp-port
          livenessProbe:
            httpGet:
              path: /healthz
              port: bggapp-port

---
# service for app
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggapp-po
  ports:
    - name: bggapp-svc-port
      port: 80
      targetPort: bggapp-port