---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: bggapp-cm
#   namespace: bggns
#   labels:
#     app: bggapp
#     name: bggapp-cm
# data:
#   BGG_DB_USER: root
#   BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ= # base64 of changeit

---